import pandas as pd


pd.set_option('display.max_columns', 5000)
pd.set_option('display.max_rows', 5000)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.width', 10000000)
air_quality_no2 = pd.read_csv('../feed/air_quality_no2_long.csv', parse_dates=True)
print(air_quality_no2.head())
print('---------------------------------------------------------------------------------------------------------------')
air_quality_no2 = air_quality_no2[['date.utc','location', 'parameter', 'value']]
print(air_quality_no2.head())
print('---------------------------------------------------------------------------------------------------------------')
air_quality_pm25 = pd.read_csv('../feed/air_quality_pm25_long.csv', parse_dates=True)
print(air_quality_pm25.head())
print('---------------------------------------------------------------------------------------------------------------')
air_quality_pm25 = air_quality_pm25[['date.utc','location', 'parameter', 'value']]
print(air_quality_pm25.head())
print('---------------------------------------------------------------------------------------------------------------')
print(air_quality_no2.count(),air_quality_no2.shape, air_quality_pm25.count(),air_quality_pm25.shape)
air_quality = pd.concat([air_quality_pm25, air_quality_no2], axis=0)
print(air_quality.count(), air_quality.shape)
print('---------------------------------------------------------------------------------------------------------------')
air_quality = air_quality.sort_values('date.utc')
print(air_quality.head())
print('---------------------------------------------------------------------------------------------------------------')
air_quality = pd.concat([air_quality_pm25, air_quality_no2], keys=["PM25", "NO2"])
print(air_quality.head())
print(air_quality['parameter'] == 'no2')
print(air_quality.count(), air_quality.shape)
print('---------------------------------------------------------------------------------------------------------------')
stations_coord = pd.read_csv('../feed/air_quality_stations.csv', parse_dates=True)
print(stations_coord.head(), stations_coord.count(), stations_coord.shape)
print('---------------------------------------------------------------------------------------------------------------')
air_quality = pd.merge(air_quality, stations_coord,how='left', on='location')
print(air_quality.head(), air_quality.count(), air_quality.shape)
print('---------------------------------------------------------------------------------------------------------------')
air_quality_parameters = pd.read_csv('../feed/air_quality_parameters.csv')
print(air_quality_parameters.head(), air_quality_parameters.count(), air_quality_parameters.shape)
print('---------------------------------------------------------------------------------------------------------------')
air_quality = pd.merge(air_quality, air_quality_parameters, how='left', left_on='parameter', right_on='name')
print(air_quality.head(), air_quality.count(), air_quality.shape)
